### ISSUE TITLE
map markers do not show up on mini map or full size map

### ISSUE THREAD

**Issue by bluenote73** [blish-hud/Community-Module-Pack#104]
Sorry if this is not a bug but an enhancement request! I get 0 markers on the mini map, or full size map, and I'm trying with several different packages.

Blish is really useful, and fast, would really love if this was fixed or added! 
thanks!

**Comment by dlamkins** [comment]
Sorry for the wait on this one.  This issue is now resolved in the replacement "Pathing" module which can be found in the latest release within the module repo.  👍
