### ISSUE TITLE
TacO Markers not showing up for Tekkit

### ISSUE THREAD

**Issue by tkrause** [blish-hud/Community-Module-Pack#105]
It seems that a lot of the Tekkit markers are just not showing up at all. They work fine in TacO however.

Specifically the Skyscales and a number of other Dragonfall markers. There are likely other affected as well. This is with a clean install and all marker enabled.

**Comment by dlamkins** [comment]
Sorry for the wait on this one.  This issue is now resolved in the replacement "Pathing" module which can be found in the latest release within the module repo.  👍
