### ISSUE TITLE
issue with certain markers

### ISSUE THREAD

**Issue by DragonHeart996** [blish-hud/Community-Module-Pack#106]
sometimes markers (noticed this with Tekkit's Workshop's Drizzlewood coast lost charr supply drop markers) will show even though their category is disabled. enabling and then disabling the category again fixes the issue, but the markers will reappear upon exiting and re-entering the map (tested by leaving to armistice bastion and then returning)

Edit: this also occurs with the eternal ice nodes markers from the same pack

**Comment by dlamkins** [comment]
Sorry for the wait on this one.  This issue is now resolved in the replacement "Pathing" module which can be found in the latest release within the module repo.  👍
