### ISSUE TITLE
Pathing copy attribute support

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#107]
**QuitarHero at 8/6/2020 5:45:49 AM +00:00**
> *nudge*  a working `copy` behavior would be swell :^)
> Around ~2/3rds done with my template here, and having people press "F" to get a build code copied to their clipboard would be fantastic

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/740807827538575400

**Comment by dlamkins** [comment]
This feature has been added in the replacement "Pathing" module which can be found in the latest release within the module repo.

https://blishhud.com/docs/markers/attributes/copy
