### ISSUE TITLE
[Markers and Paths] Some long path segments disappear

### ISSUE THREAD

**Issue by astralarya** [blish-hud/Community-Module-Pack#108]
Some long path segments just stop rendering for some reason.

To reproduce:
* Get Tekkit's All-In-One markers pack
* Go to Astralarium Waypoint [&BPoKAAA=]
* Follow path for "Part 2: Sunspear Caches"
* The path will prematurely disappear in the air at some point after jumping off the telescope

**Comment by astralarya** [comment]
The path "Part 2: Sunspear Caches" that starts at the same Waypoint also disappears as well if you follow it.  It seems to happen for long paths in the air.

**Comment by dlamkins** [comment]
Sorry for the wait on this one.  This issue is now resolved in the replacement "Pathing" module which can be found in the latest release within the module repo.  👍
