### ISSUE TITLE
Event Table does not display properly in character screen

### ISSUE THREAD

**Issue by shrykull** [blish-hud/Community-Module-Pack#136]
Hi, i really enjoy using BlishHud! 
I just stumbled upon a minor annoyance in the character screen, which i wanted to report.

The event table always works when i selected a character. In rare cases it works in character selection screen yas well, but most time it's like this for me:
When using the event table hotkey in character screen, the event table flashes for a quarter of a second or so, without any text, then disappears. 
Pressing the hotkey combination again does nothing (it probably actually makes the invisible event table disappear). 

If the hotkey is pressed a third time, the bug as described above becomes reproducible again.

Some more data: 
API permissions were given, DX11 didn't make a difference and the bug already existed in eventtable 1.4.0 and persisted through until the current version 1.4.2 (unfortunately i didnt use BlishHud earlier).

**Comment by dlamkins** [comment]
Hey, I've reached out to the owner of the module to link them here so that they'll see this report.  That module's repo is located at https://github.com/Tharylia/Blish-HUD-Event-Table/issues for future reference, though.  🙂

**Comment by Tharylia** [comment]
Hey, you can try disabling the option "hide on cutscenes". This option includes cutscenes, vista's, loading screens and the character selection.

**Comment by shrykull** [comment]
Indeed, after disabling the option the table is now consistently shown in char selection screen. thank you
