### ISSUE TITLE
Musician module gets stuck at "Loading..."

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#17]
**QuitarHero at 8/15/2019 10:49:18 AM +00:00**
> **Bug Report:**
> > **Module:** Musician `v0.60`
> > **Build:** `v0.4.1-dev+172 (Sentry)`
> Upon enabling the module, it's stuck in a "Loading..." (similar to the above report), and never fully loads due to a MouseEventArgs error, found in the log.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/611511733151989802

**Comment by TybaIt** [comment]
I think this issue is fixed? Can't replicate it anymore. Seems to have been run into prior to the name change regarding `MouseEventArgs`

**Comment by dlamkins** [comment]
Yes, I believe you're correct.  Logs seem to point to the same issue.  I think they just hadn't updated their module yet.  I'll go ahead and close.
