### ISSUE TITLE
Can't copy out waypoints from search module.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#18]
**QuitarHero at 8/23/2019 6:22:58 PM +00:00**
> **Bug Report:**
> > **Module:** Universal Search (Landmark)
> > **Build:** v0.4.2-dev+203
> **Issue:** While it searches correctly, you are unable to click any available options to copy a waypoint.
> In fact, when hovering over an option, there is no "closest waypoint" option.
> There is no temporary fix; you just cannot use this feature.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/614525006067793921

**Comment by dlamkins** [comment]
Further review suggests that I never re-implemented either of these features when the module was rebuilt using the new modular module system.

**Comment by dlamkins** [comment]
The primary feature of copying the Waypoint was fixed in #50
