### ISSUE TITLE
Wrong marker size used when iconSize is not provided (does not match TacO default)

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#42]
**QuitarHero at 2/6/2020 7:02:32 PM +00:00**
> > **Bug Report:**
> When `iconSize` is not specified, Blish defaults to the size of the `iconFile`, and not `iconSize="1"` like Taco does.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/675053735789068305

**Comment by dlamkins** [comment]
Will need to reconfirm this as it appears that the DEFAULT_ICONSIZE has been configured in `TacOMarkerPathable.cs`.

**Comment by dlamkins** [comment]
This has been resolved in the new Pathing module.
