### ISSUE TITLE
Tybalt's Feature Request [692518953259368459]

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#48]
**Tybalt at 3/25/2020 11:43:04 PM +00:00**
> Events & Meta observer needs a mute option (for the sound a notification makes.). Don't want to mute entire BlishHUD

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/692518953259368459

**Comment by TybaIt** [comment]
this is solved.

**Comment by TybaIt** [comment]
partly. Turning notifications off completely exists.
Notifications on but sound disabled still in demand.

**Comment by dlamkins** [comment]
Disabling the chime is now possible.
