### ISSUE TITLE
Allow markers to specify a default toggle state on the MarkerCategory.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#49]
**QuitarHero at 8/16/2019 5:47:10 PM +00:00**
> **Suggestion:**
> Add a category attribute for default category toggle status.
> Example:
> ```XML
> <MarkerCategory name="quest5" DisplayName="Quest 5" defaultToggle="0"/>
> ```
> Normally, all categories are toggled on by default, which can get a little overwhelming with some packs. But sometimes a pack dev would want to do this intentionally, whether for role-playing or organization purposes.
> This attribute is only considered until the user toggles a category, then it's ignored thereafter.

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/611979280280453172

**Comment by dlamkins** [comment]
This has now been implemented.  We need a wiki page (likely in this repo, but perhaps just in the Blish HUD repo) that documents this and other Blish HUD specific attributes.

**Comment by dlamkins** [comment]
Implemented in #33
