### ISSUE TITLE
Events & Metas Observer:  Add "Toggle notifications" checkbox left of sortings dropdown.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#51]
**Tybalt at 4/8/2020 3:04:30 AM +00:00**
> **Event & Metas Observer** <@!164832069401182210> 
>  should have a tick box to the left of the sort dropdown to toggle all notifications on/off. Currently, you need to disable the entire module. This is bad because often you want to check on a specific event or meta in the interface but not have the notification annoy your gameplay. It also doesn't help that you could disable each individually because then you have to reenable for when you *do* want to get notified.

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/697280685714440252

**Comment by dlamkins** [comment]
@TybaIt This is now fixed as of #50.  A checkbox has been added to the left of the sort dialog which allows you to toggle all of the modules notifications on and off.

**Comment by TybaIt** [comment]
nice :D
