### ISSUE TITLE
Markers and Paths: Behavior 4 ignores category visibility toggles

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#77]
**QuitarHero at 7/12/2020 12:35:45 PM +00:00**
> > **Bug Report:**
> > **Build:** <#534491172282957830> 
> **Issue:** Markers with `behavior="4"` *and* their respective category toggled off, when activated, will still show up after the timer expires (when they shouldn't show up at all).

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/731851291512406026

**Comment by dlamkins** [comment]
The new Pathing module has been released with this fix.
