### ISSUE TITLE
Rotate the access of the paths to allow for "walls"

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#81]
**null at 4/5/2020 1:15:01 AM +00:00**
> Add a trail property that allows certain trails to be displayed vertically to mimic capture point-esque boundaries 
> 
> more: https://discordapp.com/channels/531175899588984842/599270434642460753/696164544313032714

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/696165969332142081

**Comment by QuitarHero** [comment]
I imagine it can work similarly to a marker's `rotate` attribute, but instead x/y/z, it's simply 1 rotation; `trail-rotate="90"` makes the trail a wall; `trail-rotate="45"` or any other angle can allow trails to more fluidly traverse terrain without clipping.

**Comment by dlamkins** [comment]
This has been added with `iswall`.
