### ISSUE TITLE
Behavior to toggle culling on or off.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Community-Module-Pack#83]
**QuitarHero at 7/19/2019 10:28:18 PM +00:00**
> So a really dumb idea came into mind; because with the `rotate` attribute, people *could* make a bunch of markers and pictures, abusing `rotate` and `iconSize`, and create houses; statues, furniture, and really anything they want.
> But something that stops fun stuff like that is when using the `rotate` attribute, it only shows the image in 180 degrees; if you go behind the image, it's as if it's not there.
> Now I love how it currently is, but I would appreciate an additional argument with the `rotate` attribute that allows the image to show on both sides, not just one. a simple `0` or `1` can suffice

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/601903170939125771

**Comment by dlamkins** [comment]
The new Pathing module supports this feature now.

https://blishhud.com/docs/markers/attributes/cull
