### ISSUE TITLE
Taco Compatibility

### ISSUE THREAD

**Issue by greaka** [blish-hud/Community-Module-Pack#92]
### Checklist

 - [x] Ability to read TacO XML overlay data files into internal marker classes.
 - [x] Ability to read TacO trail (.trl) data files into internal trail classes.
 - [x] Adjust UI to compensate for TacO, if it is running.markers will need to be cached and the decision of when to load in sprites will need to be made. In the first release of this module, loading map specific sprites will likely occur when a map change event fires.
 - [x] Ability to read trail/marker files from compressed archives.
 - [x] Expose settings to UI.
#### Required
 - [x] Ability to toggle visibility for trails/marker sets.
 - [x] (not TacO specific - related to markers / trails in general) Sprites used by trails and 
 - [x] Markers and trails must support all attributes currently supported by TacO.
#### QoL
 - [ ] Ability to specify where specifically path and marker files should be automatically loaded from.
 - [ ] Option to have a prompt upon entering a map that asks which paths to enable.

### Description

In order to avoid multiple file formats and, ultimately, the duplication of hard work put in by the GW2 community, Blish HUD should be able to natively load in marker packs and trails created in or for TacO.

Additionally, Blish HUD should never assume it is the only overlay running. In the event that TacO is detected running, Blish HUD's UI icon should move over to make space (and prevent icons from overlapping).

The option to disable the display of marker packs and trails must be available so that users still using TacO have the choice to utilize it instead of Blish HUD for markers and trails.

**Comment by dlamkins** [comment]
Nearly all of these items have been implemented.  What remains is a bit different from latest roadmap, so we will close.
